#### The Basics

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c= np.zeros((3, 4))
print(c)
d = np.ones((2, 3))
print(d)
c[2,3] = 7
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 7.]]


In [15]:
#pip install numpy pandas matplotlib

In [5]:
#pip install scipy

In [2]:
import numpy as np
from scipy.linalg import lu
from scipy.linalg import lu_factor
from scipy.linalg import lu_solve

In [5]:
A = np.array([[4, -2, -3, 1], 
              [1, 3, 1, 3], [1, 2, -1, -2], [2, 1, -1, -1]])
b =np.array([20, 12, 3, 9]); b.shape = (4,1)
P,L,U =lu(A)
print(L @ U)
#print(P)
#print(L)
#print(U)

[[ 4. -2. -3.  1.]
 [ 1.  3.  1.  3.]
 [ 1.  2. -1. -2.]
 [ 2.  1. -1. -1.]]


Ill conditioned and well conditioned 

In [6]:
import numpy as np

# Create a 5x5 Hilbert matrix
n = 5
H = np.array([[1/(i+j+1) for j in range(n)] for i in range(n)])  # Note: i+j+1 for 0-indexing
b = np.ones(n)  # Simple right-hand side

cond_num = np.linalg.cond(H)
print(f"Condition number of 5x5 Hilbert matrix: {cond_num:.2e}")
# Output: Condition number is already ~4.77e+05 for n=5!
# For n=10, it's ~1.60e+13. For n=20, it's ~2.45e+28.

Condition number of 5x5 Hilbert matrix: 4.77e+05
