# Numerical Optimization With Python

*Contributors: Dr Yae GABA; Dr Aurelle TCHAGNA; Mr. Domini LEKO*

## Pre-Course 2: Numerical Linear Algebra

### Part II

In [14]:
import numpy as np
import scipy.linalg as sl

## Learning objectives:

* More on *direct* linear solver methods: the LU decomposition of a matrix


* Doolittle's algorithm


* Properties of lower-triangular matrices


* Partial pivoting

## Introduction

In Chapter 2 part 1, we developed and implemented the *Gaussian elimination* method to solve the linear matrix system 

$A\boldsymbol{x}=\boldsymbol{b}$. 

This week we will consider a closely related solution method: *LU decomposition* or *LU factorisation*.

Both are examples of *direct* solution methods - in the next lecture we will consider the alternative approach to solve linear systems, namely *iterative* or *indirect* methods.

## LU decomposition - motivation

In Chapter 2 part 1, we implemented Gaussian elimination to solve the matrix system with *one* RHS vector $\boldsymbol{b}$.  

It is often that case that we have to deal with problems where we have multiple RHS vectors, all with the same matrix $A$.

We could call the same code (e.g. our 'upper_triangle' and 'back_substitution' codes from last lecture) multiple times to solve all of these corresponding linear systems, but note that as the elimination algorithm is actually performing operations based upon (the same) $A$ each time, we would be wasting time repeating exactly the same operations over and over again - this is therefore clearly not an efficient solution to this problem.

We could easily generalise our Gaussian elimination/back substitution algorithms to include multiple RHS column vectors in the augmented system, perform the same sequence of row operations (but now only once) to transform the matrix to upper-triangular form, and then perform back substitution on each of the transformed RHS vectors from the augmented system - cf. the use of Gaussian elimination to compute the inverse to a matrix by placing the identity matrix (or equivalently the columns of the identity matrix) on the right of the augmented system: $[A|\, \textrm{col}_1,\, \textrm{col}_2, \ldots]$.

However, it is often the case that each RHS vector depends on the solutions to the matrix systems obtained from some or all of the earlier RHS vectors, and so this generalisation would not work in this case. For example, our discrete system could be of the form

$$A\boldsymbol{x}^{n+1} = \boldsymbol{b}(\boldsymbol{x}^n, \ldots)$$

where $\boldsymbol{x}^{n+1}$ is the numerical solution of a (ordinary or partial) differential equation at time level $n+1$, the RHS is a function of the the solution at the previous time level $n$ (and possibly other things such as forcing terms, represented by the "$\ldots$"). $A$ is then a discretisation of the differential equation written in the form that it maps the old solution to the new one. Time stepping this problem involves solving the same linear system multiple times, but with different RHSs. 

[NB. this is true if our model is *linear*, in the nonlinear case $A$ would be updated every time step].

## LU decomposition - theory

To deal with this situation efficiently we *decompose* or *factorise* the matrix $A$ in such a way that it is cheap to compute a new solution vector $\boldsymbol{x}$ for any given RHS vector $\boldsymbol{b}$.  This decomposition involves a lower- and an upper-triangular matrix, hence the name LU decomposition. These matrices essentially *encode* the steps conducted in Gaussian elimination, so we don't have to explicilty conduct all of the operations again and again.

Mathematically, let's assume that we have already found/constructed a lower-triangular matrix ($L$ - where all entries above the diagonal are zero) and an upper-triangular matrix ($U$ - where all entries below the diagonal are zero) such that we can write

$$ A = LU $$

In this case the matrix system we need to solve for $\boldsymbol{x}$ becomes

$$ A\boldsymbol{x} = \boldsymbol{b} \iff (LU)\boldsymbol{x} = \boldsymbol{b} \iff  L(U\boldsymbol{x}) = \boldsymbol{b} $$

Notice that the matrix-vector product $U\boldsymbol{x}$ is itself a vector, let's call it $\boldsymbol{c}$ for the time-being (i.e. 
$\boldsymbol{c}=U\boldsymbol{x}$).

The above system then reads 

$$ L\boldsymbol{c} = \boldsymbol{b} $$

where $L$ is a matrix and $\boldsymbol{c}$ is an unknown.  

As $L$ is in lower-triangular form we can use forward substitution (generalising the back subsitution algorithm/code we developed last week) to very easily find $\boldsymbol{c}$ in relatively few operations (we don't need to call the entire Gaussian elimination algorithm).

Once we know $\boldsymbol{c}$ we then solve the second linear system 

$$ U\boldsymbol{x} = \boldsymbol{c} $$

where now we can use the fact that $U$ is upper-triangular to use our back substitution algorithm again very efficiently to give the solution $\boldsymbol{x}$ we require.

So for a given $\boldsymbol{b}$ we can find the corresponding $\boldsymbol{x}$ very efficiently, we can therefore do this repeatedly as each new $\boldsymbol{b}$ is given to us.

Our challenge is therefore to find the matrices $L$ and $U$ that form the decomposition $A=LU$.


## LU decomposition - algorithm

Recall the comment above on the $L$ and $U$ matrices encoding the steps taken in Gaussian elimination.  Let's see how this works through the development of the so-called *Doolittle algorithm*.

Let's consider an example matrix:

$$
  A=\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
{\color{black}5} & {\color{black}14} & {\color{black}7} & {\color{black}10}\\
{\color{black}20} & {\color{black}77} & {\color{black}41} & {\color{black}48}\\
{\color{black}25} & {\color{black}91} & {\color{black}55} & {\color{black}67}\\
    \end{bmatrix}
$$

the first step of Gaussian elimination is to set the
sub-diagonal elements in the first column to zero by subtracting multiples of
the first row from each of the subsequent rows. 

For this example, using the symbolic notiation from last week
this requires the row operations

\begin{align}
Eq. (2) &\leftarrow Eq. (2) - 1\times Eq. (1)\\
Eq. (3) &\leftarrow Eq. (3) - 4\times Eq. (1)\\
Eq. (4) &\leftarrow Eq. (4) - 5\times Eq. (1)\\
\end{align}

or mathematically, and for each element of the matrix (remembering that we are adding rows together - while one of
the entries of a row will end up being zero, this also has the consequence of updating the rest of the values in that row, hence the iteration over $j$ below):

\begin{align}
A_{2j} &\leftarrow A_{2j} - \frac{A_{21}}{A_{11}} A_{1j} = A_{2j} - \frac{5}{5} \times A_{1j} = A_{2j} \, {\color{Orange}{-1}} \times A_{1j}, \quad j=1,2,3,4\\
A_{3j} &\leftarrow A_{3j} - \frac{A_{31}}{A_{11}} A_{1j} = A_{3j} - \frac{20}{5} \times A_{1j} = A_{3j}\, {\color{Orange}{-4}} \times A_{1j} , \quad j=1,2,3,4\\
A_{4j} &\leftarrow A_{4j} - \frac{A_{41}}{A_{11}} A_{1j} = A_{4j} - \frac{25}{5} \times A_{1j}= A_{4j}\, {\color{Orange}{-5}} \times A_{1j}, \quad j=1,2,3,4\\
\end{align}

<br>

Notice that we can also write these exact operations on elements in terms of multiplication by a carefully chosen lower-triangular matrix where the non-zero's below the diagonal are restricted to a single column, e.g. for the example above

$$
  \begin{bmatrix}
    {\color{black}1} & {\color{black}0} & {\color{black}0} & {\color{black}0}\\
    {\color{Orange}{-1}} & {\color{black}1} & {\color{black}0} & {\color{black}0}\\
    {\color{Orange}{-4}} & {\color{black}0} & {\color{black}1} & {\color{black}0}\\
    {\color{Orange}{-5}} & {\color{black}0} & {\color{black}0} & {\color{black}1}\\   
  \end{bmatrix}\qquad\times\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}5} & {\color{black}14} & {\color{black}7} & {\color{black}10}\\
    {\color{black}20} & {\color{black}77} & {\color{black}41} & {\color{black}48}\\
    {\color{black}25} & {\color{black}91} & {\color{black}55} & {\color{black}67}\\   
  \end{bmatrix}\qquad=\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{blue}{0}} & {\color{blue}{7}} & {\color{blue}{2}} & {\color{blue}{1}}\\
    {\color{blue}{0}} & {\color{blue}{49}} & {\color{blue}{21}} & {\color{blue}{12}}\\
    {\color{blue}{0}} & {\color{blue}{56}} & {\color{blue}{30}} & {\color{blue}{22}}\\    
  \end{bmatrix}
$$

the blue portion of the matrix just highlights those entries that have been affected - notice that the first column of this submatrix is by construction all zero.

The lower-triangular matrix we pre-multiply by in the above (let's call this one $L_0$) is thus encoding the first step in Gaussian elimination.

<br>

The next step involves taking the second row of the updated matrix as the new pivot (we will ignore partial pivoting for simplicity), and subtracting multiples of this row from those below in order to set the zeros below the diagonal in the second column to zero. 

Note that this step can be achieved here with the multiplication by the following lower-triangular matrix (call this one $L_1$)

\begin{equation*}
  \begin{bmatrix}
    {\color{black}1} & {\color{black}0} & {\color{black}0} & {\color{black}0}\\
    {\color{black}0} & {\color{black}1} & {\color{black}0} & {\color{black}0}\\
    {\color{black}0} & {\color{Orange}{-7}} & {\color{black}1} & {\color{black}0}\\
    {\color{black}0} & {\color{Orange}{-8}} & {\color{black}0} & {\color{black}1}\\
  \end{bmatrix}\qquad\times\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}0} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{black}0} & {\color{black}49} & {\color{black}21} & {\color{black}12}\\
    {\color{black}0} & {\color{black}56} & {\color{black}30} & {\color{black}22}\\
  \end{bmatrix}\qquad=\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}0} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{black}0} & {\color{blue}{0}} & {\color{blue}{7}} & {\color{blue}{5}}\\
    {\color{black}0} & {\color{blue}{0}} & {\color{blue}{14}} & {\color{blue}{14}}\\
  \end{bmatrix}
\end{equation*}


<br>

And finally for this example to get rid the of the leading 14 on the final row:

\begin{equation*}
  \begin{bmatrix}
    {\color{black}1} & {\color{black}0} & {\color{black}0} & {\color{black}0}\\
    {\color{black}0} & {\color{black}1} & {\color{black}0} & {\color{black}0}\\
    {\color{black}0} & {\color{black}0} & {\color{black}1} & {\color{black}0}\\
    {\color{black}0} & {\color{black}0} & {\color{Orange}{-2}} & {\color{black}{1}}\\
  \end{bmatrix}\qquad\times\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}0} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{black}0} & {\color{black}0} & {\color{black}7} & {\color{black}5}\\
    {\color{black}0} & {\color{black}0} & {\color{black}14} & {\color{black}14}\\
  \end{bmatrix}\qquad=\qquad\begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}0} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{black}0} & {\color{black}0} & {\color{black}7} & {\color{black}5}\\
    {\color{black}0} & {\color{black}0} & {\color{blue}{0}} & {\color{blue}{4}}\\
  \end{bmatrix}
\end{equation*}

where this lower triangular matrix we will call $L_2$, and the RHS matrix is now in upper-triangular form as we expect from Gaussian elimination (call this $U$).

In summary, the above operations (starting from $A$, first multiplying on the left by $L_0$, then multiplying the result on the left by $L_1$ and so on to arrive at an upper triangular matrix $U$) can be written as 

$$ L_2(L_1(L_0A)) = U $$


Note that these special lower-triangular matrices $L_0$, $L_1$ etc, are all examples of what is known as *atomic* lower-triangular matrices: a special form of unitriangular matrix (a triangular matrix with the diagonals all being unity)  where the off-diagonal entries are all zero apart from in a single column. 

Notice that for these special, simple matrices, their inverse is simply the original matrix but with the sign of those off-diagonals changed:

$$
\left[
  \begin{array}{rrrrrrrrr}
    1      & 0      & \cdots      &        &              &        &         &   & 0 \\
    0      & 1      & 0           & \cdots &              &        &         &   & 0 \\
    0      & \ddots & \ddots      & \ddots &              &        &         &   &  \vdots \\
    \vdots & \ddots & \ddots      & \ddots &              &        &         &   &  \\
           &        &             &   0    &   1          &  0     &         & &  &  \\           
           &        &             &   0    &   l_{i+1,i}  &  1     &  \ddots &   &  &  \\  
           &        &             &   0    &   l_{i+2,i}  &  0     &  \ddots &   & &  \\  
           &        &             & \vdots &   \vdots     & \vdots &  \ddots &   & 0 &  \\               
    0      & \cdots &             & 0      &   l_{n,i}    & 0      &  \cdots & 0 & 1 &  \\    
\end{array}
\right]^{-1}
=
\left[
  \begin{array}{rrrrrrrrr}
    1      & 0      & \cdots      &        &              &        &         &   & 0 \\
    0      & 1      & 0           & \cdots &              &        &         &   & 0 \\
    0      & \ddots & \ddots      & \ddots &              &        &         &   &  \vdots \\
    \vdots & \ddots & \ddots      & \ddots &              &        &         &   &  \\
           &        &             &   0    &   1          &  0     &         & &  &  \\           
           &        &             &   0    &   -l_{i+1,i}  &  1     &  \ddots &   &  &  \\  
           &        &             &   0    &   -l_{i+2,i}  &  0     &  \ddots &   & &  \\  
           &        &             & \vdots &   \vdots     & \vdots &  \ddots &   & 0 &  \\               
    0      & \cdots &             & 0      &   -l_{n,i}    & 0      &  \cdots & 0 & 1 &  \\    
\end{array}
\right]
$$

This means we can write down the product of their inverses trivially:

### <span style="color:blue">Exercise 2.21: lower-triangular matrices</span>

Convince yourselves of the following facts:


* The above statement on what the inverse of the special $L$ matrices is - check on a small example.


* The multiplication of arbitrary lower-triangular square matrices is also lower-triangular.


* $L_2(L_1(L_0A)) = U \implies A = L_0^{-1}(L_1^{-1}(L_2^{-1}U))$


* and hence that $A=LU$ where $U$ is the upper-triangular matrix found at the end of Guassian elimination, and where $L$ is the following  matrix

$$ L = L_0^{-1}L_1^{-1}L_2^{-1} $$


* Finally, compute this product of these lower-triangular matrices to show that 

$$L = 
  \begin{bmatrix}
    {\color{black}1} & {\color{black}0} & {\color{black}0} & {\color{black}0}\\
    {\color{black}{1}} & {\color{black}1} & {\color{black}0} & {\color{black}0}\\
    {\color{black}{4}} & {\color{black}7} & {\color{black}1} & {\color{black}0}\\
    {\color{black}{5}} & {\color{black}8} & {\color{black}2} & {\color{black}1}\\   
  \end{bmatrix}
$$

i.e. that the multiplication of these individual atomic matrices (importantly in this order) simply merges the entries from the non-zero columns of each atomic matrix, and hence is both lower-triangular, as well as trivial to compute.

## LU decomposition - implementation

So we can build an LU code easily from our Gaussian elimination code from last lecture which already works out and performs these tasks.  

The final $U$ matrix we need here is as was already constructed through Gaussian elimination, the entries of $L$ we need are simply the ${A_{ik}}/{A_{kk}}$ multipliers we computed as part of the elimination, but threw away previously (we called them `s` in the code and computed them outside of the `j` loop).

<br>

***Implementation observation***

For a given pivot row $k$, for each of these multipliers (for every row below the pivot), as we compute them we know that we are going to transform the augmented matrix in order to achieve a new zero below the diagonal - this frees up space in the matrix that we could use to store each multiplier moving on to the following row, we implicitly know that the diagonals of $L$ will be unity and so don't need to store these (and noting that we don't actually have a space for them anyway!). We then move on to the following pivot row, replacing the zeros in the corresponding column we are zero'ing with the multipliers again.

For example, for the case above 

$$ A = 
  \begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{black}5} & {\color{black}14} & {\color{black}7} & {\color{black}10}\\
    {\color{black}20} & {\color{black}77} & {\color{black}41} & {\color{black}48}\\
    {\color{black}25} & {\color{black}91} & {\color{black}55} & {\color{black}67}\\   
  \end{bmatrix}\quad\rightarrow\quad
  \begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{blue}{1}} & {\color{black}{7}} & {\color{black}{2}} & {\color{black}{1}}\\
    {\color{blue}{4}} & {\color{black}{49}} & {\color{black}{21}} & {\color{black}{12}}\\
    {\color{blue}{5}} & {\color{black}{56}} & {\color{black}{30}} & {\color{black}{22}}\\    
  \end{bmatrix}\quad\rightarrow\quad
  \begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{blue}1} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{blue}4} & {\color{blue}{7}} & {\color{black}{7}} & {\color{black}{5}}\\
    {\color{blue}5} & {\color{blue}{8}} & {\color{black}{14}} & {\color{black}{14}}\\
  \end{bmatrix}\quad\rightarrow\quad
  \begin{bmatrix}
    {\color{black}5} & {\color{black}7} & {\color{black}5} & {\color{black}9}\\
    {\color{blue}1} & {\color{black}7} & {\color{black}2} & {\color{black}1}\\
    {\color{blue}4} & {\color{blue}7} & {\color{black}7} & {\color{black}5}\\
    {\color{blue}5} & {\color{blue}8} & {\color{blue}{2}} & {\color{black}{4}}\\
  \end{bmatrix}
  = [\color{blue}L\backslash U]
$$



### <span style="color:blue">Exercise 2.22: LU decomposition</span>

Starting from your Gaussian elimination code (or rather the `upper_triangle` part) produce a new code to compute the LU decomposition of a matrix. First, store $L$ and $U$ in two different matrices; you could then try a version where you store the entries of both $L$ and $U$ in $A$ as described above.

NB. In my sample solution I actually don't use the trick of using the zero'd column to store the multipliers, I create a new $L$ array to store this, and return this $L$ along with the upper triangular $U$ (which will be the transformed $A$ array) from the function.

## Partial pivoting

At the end of Chapter 2 part 1, we commented that a problem would occur in a numerical implementation of our algorithm if we had a situation where the $A_{kk}$ we divide through by in the Gaussian elimination and/or back substitution algorithms was zero (or close to zero).

Using Gaussian elimination as an example, let's again consider the algorithm mid-way working on an arbitrary matrix system, i.e. assume that the first $k$ rows have already been transformed into upper-triangular form, while the equations/rows below are not yet in this form:

$$
\left[
  \begin{array}{rrrrrrr|r}
    A_{11} & A_{12} & A_{13} & \cdots & A_{1k}  & \cdots & A_{1n} & b_1 \\
    0      & A_{22} & A_{23} & \cdots & A_{2k} & \cdots & A_{2n} & b_2 \\
    0      & 0      & A_{33} & \cdots & A_{3k}  & \cdots & A_{3n} & b_3 \\
    \vdots & \vdots & \vdots & \ddots & \vdots  & \ddots & \vdots & \vdots \\
\hdashline    
    0      & 0      & 0      & \cdots & A_{kk}  & \cdots & A_{kn} & b_k \\    
    \vdots & \vdots & \vdots & \ddots & \vdots  & \ddots & \vdots & \vdots \\
    0      & 0      & 0      & \cdots & A_{nk}  & \cdots & A_{nn} & b_n \\
\end{array}
\right]
$$

Note we have drawn the horizontal dashed line one row higher than we did previously, as we are not going to simply assume without first checking that it is wise to take the current row $k$ as the pivot row, and $A_{kk}$ as the so-called pivot element.

We have a problem if $A_{kk}$ is zero as we can't use it to cancel entries below.

*Partial pivoting* is a *trick* that can be used to fix this problem. It works by using the fact that we can swap rows - we select the best pivot (row or element) as the one where the $A_{ik}$ (for $i\ge k$) value is largest (relative to the other values of components in its own row $i$), and then swaps this row with the current $k$ row.

To generalise the codes we have written so far we would simply need to search for this row, and perform the row swap operation.

Python's `scipy.linalg` library has its own implementation of the LU decomposition, and it uses partial pivoting by default - this is why it wasn't straightforward to compare our existing codes against the output of this function.

In [15]:
A = np.array([[ 5., 7.,   5.,  9.],
               [ 5., 14.,  7., 10.],
               [20., 77., 41., 48.],
               [25., 91. ,55., 67.]])
print(A)

[[ 5.  7.  5.  9.]
 [ 5. 14.  7. 10.]
 [20. 77. 41. 48.]
 [25. 91. 55. 67.]]


In [16]:
P, L , U = sl.lu(A)

# P here is a 'permutation matrix' that performs swaps based upon partial pivoting
print(P)  

# the fact that it isn't just the identity means that the scipy algorithm did indeed decide 
# to perform row swaps

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [17]:
# the lower-triangular matrix
print(L)  

[[ 1.          0.          0.          0.        ]
 [ 0.2         1.          0.          0.        ]
 [ 0.8        -0.375       1.          0.        ]
 [ 0.2         0.375       0.33333333  1.        ]]


In [18]:
# the upper-triangular matrix
print(U)  

[[ 25.          91.          55.          67.        ]
 [  0.         -11.2         -6.          -4.4       ]
 [  0.           0.          -5.25        -7.25      ]
 [  0.           0.           0.           0.66666667]]


In [19]:
# double check that P*L*U does indeed equal A
print(P @ L @ U)
print(np.allclose(A, P@L@U))

[[ 5.  7.  5.  9.]
 [ 5. 14.  7. 10.]
 [20. 77. 41. 48.]
 [25. 91. 55. 67.]]
True


By looking at the form of $P$ above, we can actually re-order the rows of $A$ in advance and consider the LU decomposition of the matrix where $P=I$, as below. 

What I mean here is that since $A = PLU$, and as $P^{-1}=P^T$, that $P^T A = LU$, so we should reorder $A$ based on what pre-multiplication by the transpose of $P$ does.

As we haven't bothered implementing pivoting ourselves yet in our own codes, we can check that our LU implementations (without partial pivoting) recreates the $A$, $L$ and $U$ below after we've done this pre-re-ordering of $A$:

In [20]:
# original A
#A = np.array([[ 5., 7.,   5.,  9.],
#               [ 5., 14.,  7., 10.],
#               [20., 77., 41., 48.],
#               [25., 91. ,55., 67.]])

# a new A with swapped rows based on observation of P
A = np.array([[25. ,91. ,55. ,67.],
               [ 5.,  7.,  5.,  9.], 
               [20., 77., 41., 48.],
               [ 5., 14., 7.,  10.]])
print(A)

[[25. 91. 55. 67.]
 [ 5.  7.  5.  9.]
 [20. 77. 41. 48.]
 [ 5. 14.  7. 10.]]


In [21]:
# this is where this comes from
A = np.array([[ 5., 7.,   5.,  9.],
               [ 5., 14.,  7., 10.],
               [20., 77., 41., 48.],
               [25., 91. ,55., 67.]])
print(P.T@A)

# we use the transpose of P since A = PLU -> P^T A = LU

[[25. 91. 55. 67.]
 [ 5.  7.  5.  9.]
 [20. 77. 41. 48.]
 [ 5. 14.  7. 10.]]


In [22]:
# a new A with swapped rows based on observation of P
A = np.array([[25. ,91. ,55. ,67.],
               [ 5.,  7.,  5.,  9.], 
               [20., 77., 41., 48.],
               [ 5., 14., 7.,  10.]])


P, L, U = sl.lu(A)
# P now should be the identity matrix as pivoting no longer actually actions any row swaps with this A
print(P)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# so this is the L we can compare our non-PP based implemetation against if we test it on this A
print(L)

[[ 1.          0.          0.          0.        ]
 [ 0.2         1.          0.          0.        ]
 [ 0.8        -0.375       1.          0.        ]
 [ 0.2         0.375       0.33333333  1.        ]]


In [24]:
# and the corresponding U
print(U)

[[ 25.          91.          55.          67.        ]
 [  0.         -11.2         -6.          -4.4       ]
 [  0.           0.          -5.25        -7.25      ]
 [  0.           0.           0.           0.66666667]]


In [25]:
print(P @ L @ U)

[[25. 91. 55. 67.]
 [ 5.  7.  5.  9.]
 [20. 77. 41. 48.]
 [ 5. 14.  7. 10.]]


### <span style="color:blue">Exercise 2.23: Partial pivoting</span>

Implement partial pivoting.